name: Deploy Nuxt3 App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Prepare SSH environment
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H 116.118.50.110 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

          ssh -i /tmp/ssh_key root@116.118.50.110 "
              cd /root/projects/music-store &&
              git pull origin main
          "
          # Sao chép thư mục .output từ GitHub Actions lên VPS
          scp -i /tmp/ssh_key -r .output/ root@116.118.50.110:/root/projects/music-store

          # Restart Docker container để áp dụng các thay đổi
          ssh -i /tmp/ssh_key root@116.118.50.110 "
            cd /root/projects/music-store &&
            sudo systemctl reload nginx
          "
